### ISSUE TITLE
why not do pull requests directly to bioconda?

### ISSUE THREAD

**Issue by rchikhi** [bonsai-team/conda_recipes#1]

**Comment by ppericard** [comment]
XD, lol, mdr...
@loic-couderc

**Comment by ppericard** [comment]
That was our first objective, and @loic-couderc worked for a while to be able to submit the matam recipe to bioconda. However, since bioconda wont support GCC 5+ until it is supported by conda-core....
So right now there is no other option to distribute MATAM through conda.

**Comment by rchikhi** [comment]
okay, fair enough
